### ISSUE TITLE
AttributeError: 'MultiTaskBatchFuse' object has no attribute 'no_sync'

### ISSUE THREAD

**Issue by xiehuanyi** [xiteng01/CVPR2023_foundation_model_Track1#5]
我在单卡上遇到了这个问题
我的cuda版本：cuda111 
python版本：python37 
torch版本：pytorch191
```
[04/13 09:21:55 ufo]: Optim:
Weight Decay, params: 
INFO - fastreid.utils.checkpoint - Loading checkpoint from /dataset/model_0054971.pdmodel/model_0054971.pdmodel
WARNING - fastreid.utils.checkpoint - heads.trafficsign.transformer.denoising_class_embed.weight has [45, 256], but heads.trafficsign.transformer.denoising_class_embed.weight has [46, 256]
WARNING - fastreid.utils.checkpoint - heads.trafficsign.transformer.denoising_class_embed.weight has [46, 256], but heads.trafficsign.transformer.denoising_class_embed.weight has [45, 256]
WARNING - fastreid.utils.checkpoint - missing keys: []
WARNING - fastreid.utils.checkpoint - unexpected keys: []
INFO - detectron2.engine.train_loop - Starting training from iteration 0
ERROR - detectron2.engine.train_loop - Exception during training:
Traceback (most recent call last):
  File "./detectron2/engine/train_loop.py", line 154, in train
    self.run_step()
  File "./detectron2/engine/train_loop.py", line 303, in run_step
    with self.model.no_sync():
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1123, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'MultiTaskBatchFuse' object has no attribute 'no_sync'
INFO - detectron2.engine.hooks - Total training time: 0:00:00 (0:00:00 on hooks)
INFO - detectron2.utils.events -  iter: 0    lr: N/A  
ERROR - /model - Failed after 0:04:39!
Traceback (most recent call last):
  File "tools/ufo_train.py", line 231, in <module>
    main(args)
  File "tools/ufo_train.py", line 223, in main
    ex.run(config_updates={'args': args, 'cfg_for_sacred': LazyConfig.to_dict(cfg)})
  File "/opt/conda/lib/python3.7/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/opt/conda/lib/python3.7/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/opt/conda/lib/python3.7/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "tools/ufo_train.py", line 219, in do_train_sacred
    do_train(args, cfg, cfg_for_sacred, _run)
  File "tools/ufo_train.py", line 162, in do_train
    trainer.train(start_iter, cfg.train.max_iter)
  File "./detectron2/engine/train_loop.py", line 154, in train
    self.run_step()
  File "./detectron2/engine/train_loop.py", line 303, in run_step
    with self.model.no_sync():
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1123, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'MultiTaskBatchFuse' object has no attribute 'no_sync'
INFO 2023-04-13 09:23:14,858 launch_utils.py:343] terminate all the procs
INFO 2023-04-13 09:23:14,858 launch_utils.py:343] terminate all the procs
ERROR 2023-04-13 09:23:14,859 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2023-04-13 09:23:14,859 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2023-04-13 09:23:18,862 launch_utils.py:343] terminate all the procs
INFO 2023-04-13 09:23:18,862 launch_utils.py:343] terminate all the procs
INFO 2023-04-13 09:23:18,862 launch.py:402] Local processes completed.
INFO 2023-04-13 09:23:18,862 launch.py:402] Local processes completed.```

**Comment by South2North** [comment]
可以试一下安装这里对应的paddle版本：paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by yr-zh** [comment]
同样的问题，请问你解决没有

**Comment by xiehuanyi** [comment]
我是单卡上训练的 所以这些应该是不需要的 我把数据并行的那段代码删除了 但是又遇到了其他的一些问题



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月17日 22:16 |
| 收件人 | ***@***.***> |
| 抄送至 | Huanyi ***@***.***>***@***.***> |
| 主题 | Re: [xiteng01/CVPR2023_foundation_model_Track1] AttributeError: 'MultiTaskBatchFuse' object has no attribute 'no_sync' (Issue #5) |

同样的问题，请问你解决没有

**Comment by yr-zh** [comment]
好的，我也删了试一下
